const limitNum = {
  EVENT_NAME_MAX_LENGTH: 10,
  EVENT_CNT: 10,
  RULE_CATEGORY_NAME_MAX_LENGTH: 5,
  RULE_CATEGORY_CNT: 10,
  RULE_NAME_MAX_LENGTH: 15,
  RULE_CNT: 20,
  PROFILE_NAME_MAX_LENGTH: 5,
  PROFILE_JOB_MAX_LENGTH: 5,
  PROFILE_INTRODUCTION_MAX_LENGTH: 20,
  PROFILE_HASH_TAG_MAX_LENGTH: 5,
  PROFILE_HASH_TAG_CNT: 3,
  TYPES_AT_RULE_BY_CATEGORY_CNT: 3
};

export default limitNum;
